import Form from './src/controls/form/form';
import FormDropdown from './src/controls/dropdown/dropdown';
import FormTextInput from './src/controls/textInput/textInput';
import FormPasswordInput from './src/controls/textInput/passwordInput';
import FormCpfInput from './src/controls/textInput/cpfInput';
import FormDateInput from './src/controls/textInput/dateInput';
import FormEmailInput from './src/controls/textInput/emailInput';
import FormPhoneInput from './src/controls/textInput/phoneInput';
import FormZipCodeInput from './src/controls/textInput/zipCodeInput';
import FormAgeInput from './src/controls/textInput/ageInput';

module.exports.Form = Form;
module.exports.FormDropdown = FormDropdown;
module.exports.FormTextInput = FormTextInput;
module.exports.FormPasswordInput = FormPasswordInput;
module.exports.FormCpfInput = FormCpfInput;
module.exports.FormDateInput = FormDateInput;
module.exports.FormEmailInput = FormEmailInput;
module.exports.FormPhoneInput = FormPhoneInput;
module.exports.FormZipCodeInput = FormZipCodeInput;
module.exports.FormAgeInput = FormAgeInput;
